[package]
name = "unicity-arpc"
version = "0.0.0"
edition = "2024"

[dependencies]
jsonrpsee = { version = "0.26.0", features = ["http-client"] }
thiserror.workspace = true
serde.workspace = true

[lints]
workspace = true
