[advisories]
ignore = [
    "RUSTSEC-2024-0388", # derivative crate is unmaintained, check ark-*
    "RUSTSEC-2024-0436", # paste crate is unmaintained, check risc0-*
]
[licenses]
allow = [
    "MIT",
    "MITNFA", # MIT variant, compatible with MIT
    "Apache-2.0", # Compatible with MIT
    "BSD-3-Clause", # Compatible with MIT
    "CC0-1.0", # Public domain, compatible with MIT
    "MPL-2.0", # Weak copyleft, compatible with MIT
    "Unicode-3.0", # Unicode license, compatible with MIT
]
confidence-threshold = 0.8
