[alias]
# Strict clippy that catches security issues
check-strict = "clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used -D clippy::panic -D clippy::unimplemented -D clippy::todo -D clippy::unreachable -D clippy::indexing_slicing -D clippy::integer_arithmetic -D clippy::float_arithmetic"

# Security-focused clippy
check-security = "clippy -- -D warnings -D clippy::unwrap_used -D clippy::expect_used -D clippy::panic -D clippy::integer_overflow -D clippy::cast_lossless -D clippy::cast_possible_truncation -D clippy::cast_possible_wrap -D clippy::cast_sign_loss"
